# Alacritty Configuration for a Minimalist Graphic Designer

# Window settings
window:
  # remove top bar of window
  decorations: buttonless 
  # Dimensions (Columns x Rows)
  dimensions:
    columns: 100
    lines: 30
  # Transparency settings
  background_opacity: 0.5
  padding:
    x: 200  # Horizontal padding
    y: 100  # Vertical padding

# Font settings
font:
  # Modern, clean font
  normal:
    family: "Fira Code"
    style: Regular
  size: 28.0
  offset:
    x: 0  # For letter spacing (default: 0)
    y: 70  # For line spacing (adjust the value as needed)

# Color scheme
colors:
  # Using a simple and elegant color palette
  primary:
    background: '0x000000'
    foreground: '0x999999'
  cursor:
    text:   '0x999999'
    cursor: '0x999999'

# Mouse settings
mouse:
  # Disabling mouse acceleration for precision
  acceleration: 0

# Scrolling settings
scrolling:
  # Smooth scrolling
  multiplier: 4
