[colors.cursor]
cursor = "0x999999"
text = "0x999999"

[colors.primary]
background = "0x000000"
foreground = "0x999999"

[font]
size = 20
offset.y = 40
glyph_offset.y = 20

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[scrolling]
multiplier = 2

[window]
decorations = "buttonless"

[window.dimensions]
columns = 48
lines = 8

[window.padding]
x = 25
