theme = { dark = "dark", light = "light" }

[editor]
bufferline = "multiple"
line-number = "relative"
mouse = false
auto-format = true
auto-completion = true
path-completion = true

[editor.lsp]
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
auto-document-highlight = true

[keys.insert]
"C-c" = "normal_mode"
j = { k = "normal_mode" }
C-s = ":w"

[keys.normal]
x = "select_line_below"
X = "select_line_above"
C-s = ":w"
