[theme]
dark = "dark"
light = "light"
fallback = "dark"

[editor]
bufferline = "multiple"
line-number = "relative"
mouse = false
auto-format = true
auto-completion = true
path-completion = true
# rulers = [80, 120]

[editor.indent-guides]
render = false
# character = "│"
# skip-levels = 0

[editor.lsp]
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
auto-document-highlight = true


[keys.insert]
"C-c" = "normal_mode"
j = { k = "normal_mode" }
C-s = ":w"

[keys.normal]
x = "select_line_below"
X = "select_line_above"
C-s = ":w"
C-x = ":x"
