(require "smooth-scroll/smooth-scroll.scm")
(require "showkeys/showkeys.scm")
(require "nrepl.scm")
(require "jj/jj.scm")
(require "cogs/keymaps.scm")
(require "helix-file-watcher/file-watcher.scm")
(require "steel-pty/term.scm")

(require (prefix-in helix. "helix/commands.scm"))
(require (prefix-in helix.static. "helix/static.scm"))

(require-builtin steel/random as rand::)

(keymap (global)
  (normal (space (n (C ":nrepl-connect")
                  (D ":nrepl-disconnect")
                  (b ":nrepl-eval-buffer")
                  (m ":nrepl-eval-multiple-selections")
                  (p ":nrepl-eval-prompt")
                  (s ":nrepl-eval-selection")))
    (A-ret ":nrepl-eval-selection"))
  (select (space (n (C ":nrepl-connect")
                  (D ":nrepl-disconnect")
                  (b ":nrepl-eval-buffer")
                  (m ":nrepl-eval-multiple-selections")
                  (p ":nrepl-eval-prompt")
                  (s ":nrepl-eval-selection")))
    (A-ret ":nrepl-eval-selection")))
