# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

set -gx LAKE /Users/nobr/desk/lake

bind \cz 'fg 2>/dev/null; commandline -f repaint' # ctrl z to reopen hx

source /nix/store/p8870c40wka5chg6yk08d9kwxx79k9ac-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    #
    direnv hook fish | source

    # Aliases
    alias cat bat
    alias cd z
    alias eza 'eza --icons auto --git'
    alias grep rg
    alias la 'eza -a'
    alias less bat
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'
    # alias man tldr
    alias vimdiff 'nvim -d'
    alias t dstask

    # Interactive shell initialisation
    /nix/store/80hwwq3k3xhmhvd2my22px2nwi0kng23-fzf-0.62.0/bin/fzf --fish | source

    /nix/store/8p5y6id6dc082rfsgznlzkyxlcqm6dvs-zoxide-0.9.8/bin/zoxide init fish | source

    if test "$TERM" != dumb
        /nix/store/k1k1zwpqn5gfgdqql1z5g18i5vzrva3n-starship-1.23.0/bin/starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/nobr/.local/share/fish/home-manager_generated_completions" $post
    end

end

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/nobr/google-cloud-sdk/path.fish.inc' ]
    . '/Users/nobr/google-cloud-sdk/path.fish.inc'
end
