# dark.toml
inherits = "lilka"

[palette]
text         = "#ffffff"
strong       = "#e6e6e6"
mid          = "#c2c2c2"
muted        = "#999999"
subtle       = "#737373"
faint        = "#595959"
ghost        = "#404040"
mist         = "#333333"

cursor       = "#ffffff"
cursorline   = "#404040"
selection    = "#c2c2c2"

inlay        = "#666666"
inlay_strong = "#999999"
